version: '3.8'  
services:  
  db:  
    container_name: postgres_db  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:  
      - "5432:5432"  
  mq:
    container_name: rabbit_mq
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"